### ISSUE TITLE
Filtered index `get_current_index` receives a `None` value

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#2105]
## Airflow log link

> **Note**: _Airflow is currently only accessible to maintainers & those given
> access. If you would like access to Airflow, please reach out to a member of
> @WordPress/openverse-maintainers_.

https://airflow.openverse.engineering/log?execution_date=2023-05-15T18%3A42%3A21.244399%2B00%3A00&task_id=get_current_index&dag_id=create_filtered_audio_index&map_index=-1

## Description

```
[2023-05-15, 18:52:28 UTC] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/http/operators/http.py", line 134, in execute
    return self.response_filter(response, **kwargs)
  File "/opt/airflow/catalog/dags/common/ingestion_server.py", line 30, in response_filter_stat
    _, index_suffix = index_name.split("-", maxsplit=1)
AttributeError: 'NoneType' object has no attribute 'split'
```

## Reproduction

This occurred across several retries.

## DAG status

I have paused the DAG while we create a fix.

**Comment by AetherUnbound** [comment]
I strongly suspect this is just because this was the first time we ran the DAG and so the index does not yet exist.

**Comment by AetherUnbound** [comment]
Yep!
```
[ec2-user@ip-172-31-73-104 ~]$ curl -w "\n" -L http://ingestion.private:8001/stat/autio-filtered
{"exists": false, "is_alias": null, "alt_names": null}
```
