### ISSUE TITLE
[Nuxt 3] Playwright Docker build fails on MacOS

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#3694]
## Description

The Playwright tests do not run locally on MacOS due to a build error.

## Reproduction

1. Run `just frontend/run test:playwright`
2. See error:
```
playwright-1  | > pnpm build:only && pnpm start
playwright-1  | 
playwright-1  | [WebServer] 
playwright-1  | > @openverse/frontend@2.2.1 build:only /frontend
playwright-1  | > NODE_ENV=production nuxt build
playwright-1  | 
playwright-1  | 2024-01-23T13:51:30.446Z pw:webserver Waiting 1000ms
playwright-1  | [WebServer] Nuxt 3.9.1 with Nitro 2.8.1
playwright-1  | 2024-01-23T13:51:31.448Z pw:webserver Waiting 1000ms
playwright-1  | [WebServer] 
playwright-1  |  ERROR  Cannot find module @rollup/rollup-linux-arm64-gnu. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try npm i again after removing both package-lock.json and node_modules directory.
playwright-1  | 
playwright-1  |   at requireWithFriendlyError (/node_modules/.pnpm/rollup@4.9.4/node_modules/rollup/dist/native.js:87:9)
playwright-1  |   at Object.<anonymous> (/node_modules/.pnpm/rollup@4.9.4/node_modules/rollup/dist/native.js:96:48)
playwright-1  |   at Module._compile (node:internal/modules/cjs/loader:1376:14)
playwright-1  |   at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
playwright-1  |   at Module.load (node:internal/modules/cjs/loader:1207:32)
playwright-1  |   at Module._load (node:internal/modules/cjs/loader:1023:12)
playwright-1  |   at cjsLoader (node:internal/modules/esm/translators:345:17)
playwright-1  |   at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:294:7)
playwright-1  |   at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
playwright-1  |   at async ModuleLoader.import (node:internal/modules/esm/loader:329:24) 
playwright-1  | 
playwright-1  | 
playwright-1  | [WebServer] 
playwright-1  |  ERROR  Cannot find module @rollup/rollup-linux-arm64-gnu. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try npm i again after removing both package-lock.json and node_modules directory.
playwright-1  | 
playwright-1  | [WebServer]  ELIFECYCLE  Command failed with exit code 1.
playwright-1  | [WebServer]  ELIFECYCLE  Command failed with exit code 1.
playwright-1  | [WebServer]  ELIFECYCLE  Command failed with exit code 1.
playwright-1  | [WebServer]  ELIFECYCLE  Command failed.
playwright-1  | 2024-01-23T13:51:32.449Z pw:webserver Waiting 1000ms
playwright-1  | [WebServer] Talkback started at http://localhost:49153 with record mode DISABLED
playwright-1  | [WebServer] Received SIGTERM
playwright-1  | [WebServer] Server closed, exiting process
playwright-1  | [WebServer] ERROR: "prod:playwright" exited with 1.
playwright-1  | Error: Process from config.webServer was not able to start. Exit code: 1

```

## Environment

- Device:  MacBook Pro M2
- OS:  MacOS

## Additional context

Priority `medium` because the tests can run in GitHub actions.

**Comment by dhruvkb** [comment]
Closing for now as we've decided to attempt the Nuxt 3 migration again in a few months once the ecosystem is more mature.
