### ISSUE TITLE
Investigate recent iNaturalist failures

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#4103]
## Airflow log link

> **Note**: _Airflow is currently only accessible to maintainers & those given
> access. If you would like access to Airflow, please reach out to a member of
> @WordPress/openverse-maintainers_.

Nearly all of the load steps failed, but here's the first that triggered the cascade of the rest:
https://airflow.openverse.org/dags/inaturalist_workflow/grid?dag_run_id=scheduled__2024-03-02T00%3A00%3A00%2B00%3A00&task_id=ingest_data.load_image_data.load_transformed_data&tab=mapped_tasks&map_index=65

Example of the cascade:
https://airflow.openverse.org/dags/inaturalist_workflow/grid?dag_run_id=scheduled__2024-03-02T00%3A00%3A00%2B00%3A00&task_id=ingest_data.load_image_data.load_transformed_data&tab=mapped_tasks&map_index=69

## Description

It looks like that first load failure timed out:

<details> <summary>Timeout exception</summary>

```
[2024-04-04, 03:28:10 UTC] {base.py:83} INFO - Using connection ID 'postgres_openledger_upstream' for task execution.
[2024-04-04, 03:28:10 UTC] {sql.py:457} INFO - Running statement: SET statement_timeout TO '3600.0s'; 
    INSERT INTO image AS old
    (url, created_on, updated_on, ingestion_type, provider, source, foreign_identifier, foreign_landing_url, thumbnail, width, height, filesize, license, license_version, creator, creator_url, title, meta_data, tags, watermarked, last_synced_with_source, removed_from_source, filetype, category, standardized_popularity)
    SELECT DISTINCT ON (url) url,
    NOW(), NOW(), ingestion_type, provider, source, foreign_identifier, foreign_landing_url, thumbnail, width, height, filesize, license, license_version, creator, creator_url, title, meta_data, tags, watermarked, NOW(), 'f', filetype, category, standardized_image_popularity(provider, meta_data)
    FROM load_image_20240302T000000 as new
    WHERE NOT EXISTS (
        SELECT url from image
        WHERE url = new.url AND
            MD5(foreign_identifier) <> MD5(new.foreign_identifier)
    )
    ON CONFLICT (provider, md5(foreign_identifier))
    DO UPDATE SET
    updated_on = NOW(),
ingestion_type = COALESCE(EXCLUDED.ingestion_type, old.ingestion_type),
provider = COALESCE(EXCLUDED.provider, old.provider),
source = COALESCE(EXCLUDED.source, old.source),
foreign_identifier = COALESCE(EXCLUDED.foreign_identifier, old.foreign_identifier),
foreign_landing_url = COALESCE(EXCLUDED.foreign_landing_url, old.foreign_landing_url),
url = COALESCE(EXCLUDED.url, old.url),
thumbnail = COALESCE(EXCLUDED.thumbnail, old.thumbnail),
width = COALESCE(EXCLUDED.width, old.width),
height = COALESCE(EXCLUDED.height, old.height),
filesize = COALESCE(EXCLUDED.filesize, old.filesize),
license = COALESCE(EXCLUDED.license, old.license),
license_version = COALESCE(EXCLUDED.license_version, old.license_version),
creator = COALESCE(EXCLUDED.creator, old.creator),
creator_url = COALESCE(EXCLUDED.creator_url, old.creator_url),
title = COALESCE(EXCLUDED.title, old.title),
meta_data = COALESCE(
       jsonb_strip_nulls(old.meta_data)
         || jsonb_strip_nulls(EXCLUDED.meta_data),
       EXCLUDED.meta_data,
       old.meta_data
     ),
tags = COALESCE(
       (
         SELECT jsonb_agg(DISTINCT x)
         FROM jsonb_array_elements(old.tags || EXCLUDED.tags) t(x)
       ),
       EXCLUDED.tags,
       old.tags
     ),
watermarked = COALESCE(EXCLUDED.watermarked, old.watermarked),
last_synced_with_source = NOW(),
removed_from_source = 'f',
filetype = COALESCE(EXCLUDED.filetype, old.filetype),
category = COALESCE(EXCLUDED.category, old.category),
standardized_popularity = standardized_image_popularity(EXCLUDED.provider, EXCLUDED.meta_data)
, parameters: None
[2024-04-04, 04:26:53 UTC] {timeout.py:68} ERROR - Process timed out, PID: 6597
[2024-04-04, 04:26:53 UTC] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 439, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/catalog/dags/providers/provider_api_scripts/inaturalist.py", line 145, in load_transformed_data
    upserted_records = sql.upsert_records_to_db_table(
  File "/opt/airflow/catalog/dags/common/utils.py", line 71, in wrapped
    return func(*args, **kwargs)
  File "/opt/airflow/catalog/dags/common/utils.py", line 71, in wrapped
    return func(*args, **kwargs)
  File "/opt/airflow/catalog/dags/common/loader/sql.py", line 333, in upsert_records_to_db_table
    return postgres.run(upsert_query, handler=RETURN_ROW_COUNT)
  File "/opt/airflow/catalog/dags/common/sql.py", line 90, in run
    return super().run(sql, autocommit, parameters, handler)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 404, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 462, in _run_command
    cur.execute(sql_statement)
  File "/usr/local/lib/python3.10/encodings/utf_8.py", line 15, in decode
    def decode(input, errors='strict'):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: Timeout, PID: 6597
```

</details>

Each of the subsequent failures then failed saying the load table is missing:

```
[2024-04-04, 04:27:07 UTC] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 439, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/catalog/dags/providers/provider_api_scripts/inaturalist.py", line 127, in load_transformed_data
    (loaded_records, max_id_loaded) = pg.get_records(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 267, in get_records
    return self.run(sql=sql, parameters=parameters, handler=fetch_all_handler)
  File "/opt/airflow/catalog/dags/common/sql.py", line 90, in run
    return super().run(sql, autocommit, parameters, handler)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 404, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 462, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedTable: relation "load_image_20240302t000000" does not exist
LINE 17: INSERT INTO load_image_20240302T000000
                     ^
```

I _suspect_ what happened is that the failure of the mapped task immediately triggered the downstream steps, even though the mapped task itself was still running. This meant that the cleanup steps ran after the first failure _while the rest of mapped tasks were still running_, which then failed because the load table had been deleted out from under them.

This can actually be seen by the timestamps too: The mapped tasks continue until 2024-04-04, 04:36:46 UTC, but the load table step starts at 2024-04-04, 04:26:59 UTC.

## Reproduction

I've been able to reproduce this behavior locally with the following DAG:

```python
from datetime import datetime
from time import sleep

from airflow.decorators import task
from airflow.models.dag import DAG

with DAG(
    dag_id="dynamic_task_mapping_check",
    start_date=datetime(2022, 3, 4),
    catchup=False,
) as dag:

    @task
    def add_one(x: int):
        sleep(x * 2)
        if x == 2:
            raise ValueError("x is 2!")
        return x + 1

    @task
    def sum_it(values):
        total = sum(values)
        print(f"Total was {total}")

    @task(trigger_rule="none_skipped")
    def run_only_on_all_success(values):
        print(f"Ran at {datetime.now()}")
        print(f"Values were {values}")

    added_values = add_one.expand(x=[1, 2, 3, 4, 5])
    sum_it(added_values)
    run_only_on_all_success(added_values)
```

Running this will cause the tasks at the end to wait until all of the successful mapped tasks are completed. This means Airflow _should_ be behaving sensibly here, so I'll need to dig a little deeper.

## Screenshots

![image](https://github.com/WordPress/openverse/assets/10214785/bc146a5c-602b-4e02-ac87-635caaae8b71)

## DAG status

Not paused because it won't be run again for a few months.

**Comment by AetherUnbound** [comment]
I've got it, this DAG is able to reproduce the problem:

```python
from airflow.utils.task_group import TaskGroup
from datetime import datetime
from time import sleep

from airflow.decorators import task
from airflow.models.dag import DAG

with DAG(
    dag_id="dynamic_task_mapping_check",
    start_date=datetime(2022, 3, 4),
    catchup=False,
) as dag:

    @task
    def add_one(x: int):
        sleep(x * 2)
        if x == 2:
            raise ValueError("x is 2!")
        return x + 1

    @task
    def sum_it(values):
        total = sum(values)
        print(f"Total was {total}")

    @task(trigger_rule="none_skipped")
    def run_only_on_all_success(values):
        print(f"Ran at {datetime.now()}")
        print(f"Values were {values}")

    with TaskGroup("add_one_group") as add_one_group:
        @task(trigger_rule="none_skipped")
        def run_only_on_all_success_no_input():
            print(f"Ran at {datetime.now()}")

        run_only_on_all_success_no_input()

    added_values = add_one.expand(x=[1, 2, 3, 4, 5])
    x = sum_it(added_values)
    x >> run_only_on_all_success(added_values)
    x >> add_one_group
```

In the example here, `sum_it` moves to state `upstream_failed` _as soon as_ the first mapped task fails. Any steps thereafter read the `upstream_failed` as valid for their `none_skipped` trigger, and so thus run (ahead of when we'd actually like them to). This should be resolvable by changing the trigger rule for the step right after the mapped task.

**Comment by AetherUnbound** [comment]
V3 of this code is I think what we want:

```python
from airflow.operators.empty import EmptyOperator
from airflow.utils.task_group import TaskGroup
from airflow.utils.trigger_rule import TriggerRule
from datetime import datetime
from time import sleep

from airflow.decorators import task
from airflow.models.dag import DAG

with DAG(
    dag_id="dynamic_task_mapping_check",
    start_date=datetime(2022, 3, 4),
    catchup=False,
) as dag:

    with TaskGroup("big_one") as big_one:

        @task
        def add_one(x: int):
            sleep(x * 2)
            if x == 2:
                raise ValueError("x is 2!")
            return x + 1

        @task
        def sum_it(values):
            total = sum(values)
            print(f"Total was {total}")

        added_values = add_one.expand(x=[1, 2, 3, 4, 5])
        sum_it(added_values)

        e = EmptyOperator(task_id="empty", trigger_rule=TriggerRule.ALL_DONE)
        added_values >> e

    @task(trigger_rule="none_skipped")
    def run_only_on_all_success():
        print(f"Ran at {datetime.now()}")

    @task
    def should_fail():
        print("This should be failed upstream")

    with TaskGroup("add_one_group") as add_one_group:

        @task(trigger_rule=TriggerRule.NONE_SKIPPED)
        def run_only_on_all_success_no_input():
            print(f"Ran at {datetime.now()}")

        run_only_on_all_success_no_input()

    big_one >> run_only_on_all_success()
    big_one >> add_one_group
    big_one >> should_fail()
```

In this case, the task outside of the task group (`should_fail`) will get upstream failed right after `sum_it` because that's the default behavior for default trigger rules. The `EmptyOperator` ensures that the entire task group waits until the mapped task is done, and then the downstream tasks are able to run successfully (after the `EmptyOperator` completes, which is after the mapped task finishes _all_ of its parameters). Here's an example run:

![image](https://github.com/WordPress/openverse/assets/10214785/cad5f4b4-f9e5-44c2-a9c8-7d3c79c18ecb)
