### ISSUE TITLE
`just api/pgcli` is broken

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#4185]
## Description

It looks like #4184 might have affected our ability to run `pgcli` for the API. When I run `just api/pgcli`, I get the following error:

```
env COMPOSE_PROFILES="api,ingestion_server,frontend,catalog" docker compose -f docker-compose.yml exec -u opener web pgcli postgresql://deploy:deploy@db:5432/openledger
WARN[0000] /home/madison/git-a8c/openverse/docker-compose.yml: `version` is obsolete 
Traceback (most recent call last):
  File "/.venv/bin/pgcli", line 5, in <module>
    from pgcli.main import cli
  File "/.venv/lib/python3.11/site-packages/pgcli/main.py", line 52, in <module>
    from .pgtoolbar import create_toolbar_tokens_func
  File "/.venv/lib/python3.11/site-packages/pgcli/pgtoolbar.py", line 1, in <module>
    from pkg_resources import packaging
ModuleNotFoundError: No module named 'pkg_resources'
error: Recipe `dc` failed on line 160 with exit code 1
error: Recipe `exec` failed on line 229 with exit code 1
error: Recipe `_pgcli` failed on line 237 with exit code 1
error: Recipe `pgcli` failed on line 90 with exit code 1
```

## Reproduction

1. Checkout `main`
2. Run `just build`
3. Run `just api/init`
4. Run `just api/pgcli` and observe the above error

**Comment by zackkrida** [comment]
ModuleNotFoundError: No module named 'pkg_resources' refers to `setuptools` not being installed. Perhaps we need to declare it explicitly somewhere?

**Comment by dhruvkb** [comment]
I think we need to add `setuptools` as a dependency using `pdm add setuptools`. I'll do this right away.
