### ISSUE TITLE
iNaturalist is no longer able to access S3

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#4255]
## Airflow log link

> **Note**: _Airflow is currently only accessible to maintainers & those given
> access. If you would like access to Airflow, please reach out to a member of
> @WordPress/openverse-maintainers_.

https://airflow.openverse.org/dags/inaturalist_workflow/grid?task_id=ingest_data.preingestion_tasks.check_for_file_updates&dag_run_id=scheduled__2024-04-02T00%3A00%3A00%2B00%3A00&tab=logs

```
[2024-05-02, 00:10:09 UTC] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 460, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/catalog/dags/providers/provider_api_scripts/inaturalist.py", line 205, in compare_update_dates
    last_modified = s3_client.head_object(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 553, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 1009, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden
```

## Description

It appears that the iNaturalist DAG is no longer able to access the S3 bucket (`inaturalist-open-data`) which contains the iNaturalist source data.

## DAG status

Unchanged while we investigate.

**Comment by sarayourfriend** [comment]
This is an IAM issue. The bucket needs to be added to the list of buckets allowed access to Airflow in https://github.com/WordPress/openverse-infrastructure/blob/981b327a0e624d57f1efa51215ffcc16c0f19a22/next/production/airflow.tf#L105-L129

**Comment by krysal** [comment]
Reopening to confirm the problem is solved after a catalog deployment.

**Comment by AetherUnbound** [comment]
@krysal If the policy change has already been applied, I believe that should be immediate! I think we can restart the iNaturalist DAG without having to wait for a redeployment.

**Comment by sarayourfriend** [comment]
Correct, policy changes take effect immediately, they're tied to the instance _profile_, not the instance itself.

**Comment by AetherUnbound** [comment]
The DAG is once again running, confirmed this has been resolved.
