### ISSUE TITLE
Documentation install fails in dev environment

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#5146]
## Description

When trying to run `ov just documentation/install`, I'm seeing the following:

```bash
$ ov just documentation/install
pdm install 
Synchronizing working set with resolved packages: 1 to add, 0 to update, 0 to remove

  ✖ Install watchfiles 0.21.0 failed
  ✖ Install watchfiles 0.21.0 failed

ERRORS:
add watchfiles failed:
Traceback (most recent call last):
  File "/usr/lib64/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pipx/venvs/pdm/lib64/python3.12/site-packages/pdm/installers/synchronizers.py", line 29, in install_candidate
    self.manager.install(can)
  File "/pipx/venvs/pdm/lib64/python3.12/site-packages/pdm/installers/manager.py", line 33, in install
    prepared.build(),
    ^^^^^^^^^^^^^^^^
  File "/pipx/venvs/pdm/lib64/python3.12/site-packages/pdm/models/candidates.py", line 411, in build
    self._cached = Path(builder.build(build_dir, metadata_directory=self._metadata_dir))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pipx/venvs/pdm/lib64/python3.12/site-packages/pdm/builders/base.py", line 84, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/pipx/venvs/pdm/lib64/python3.12/site-packages/pdm/builders/wheel.py", line 26, in build
    filename = self._hook.build_wheel(out_dir, self.config_settings, metadata_directory)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pipx/venvs/pdm/lib64/python3.12/site-packages/pyproject_hooks/_impl.py", line 256, in build_wheel
    return self._call_hook(
           ^^^^^^^^^^^^^^^^
  File "/pipx/venvs/pdm/lib64/python3.12/site-packages/pyproject_hooks/_impl.py", line 392, in _call_hook
    self._subprocess_runner(
  File "/pipx/venvs/pdm/lib64/python3.12/site-packages/pdm/builders/base.py", line 281, in subprocess_runner
    return log_subprocessor(cmd, cwd, extra_environ=env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pipx/venvs/pdm/lib64/python3.12/site-packages/pdm/builders/base.py", line 128, in log_subprocessor
    raise build_error(e) from None
pdm.exceptions.BuildError: Build backend raised error: Showing the last 10 lines of the build output:
Running `maturin pep517 build-wheel -i /opt/pdm/venvs/documentation-9jJgBbYH-3.12/bin/python --compatibility off`
💥 maturin failed
  Caused by: Cargo metadata failed. Do you have cargo in your PATH?
  Caused by: No such file or directory (os error 2)
Error: command ['maturin', 'pep517', 'build-wheel', '-i', '/opt/pdm/venvs/documentation-9jJgBbYH-3.12/bin/python', '--compatibility', 'off'] returned non-zero exit status 1

  0:00:00 ✖ Some package operations failed. 1/1
See /opt/.local/state/pdm/log/pdm-install-0kwtruue.log for detailed debug log.
[InstallationError]: Some package operations failed.
WARNING: Add '-v' to see the detailed traceback
error: Recipe `install` failed on line 16 with exit code 1
```

This is after running `ov clean` and `ov build` and `ov just build`.

## Reproduction

1. Run `ov just documentation/install`
2. Observe the above error

## Additional context

This thread would indicate we either need to install `rust` on the box, update `pip`, or install a different version of the library: https://stackoverflow.com/questions/71696582/issue-with-installing-packages-with-pip-cargo-the-rust-package-manager-is-no

**Comment by dhruvkb** [comment]
`watchfiles` caused issues in the Python upgrade too, updating it (as done in  https://github.com/WordPress/openverse/pull/5095/commits/7a2ded7164bad019723db5973aa23c34f6a20332) fixed the Rust issues. Could you try that and see if it fixes the problem?

**Comment by AetherUnbound** [comment]
Will do!
